### ISSUE TITLE
Feature suggestion: (Re)introduce U18, U16, U14 filters in the view of registered participants.

### ISSUE THREAD

**Issue by dreirund** [cde-ev/cdedb2#1]
Ahoj,

I have a feature suggestion:

In the view of the registrations for an event, (re)introduce the pre-defined filters for people below 18, below 16 and below 14 years of age.

Rationale: This is needed quite commonly, and doing this filter by hand is a typical thing for of-by-one errors when calculating the year cutoff. ("When does someone get 18? Year of birth + 18 years? Year of birth + 17 years? Year of birth + 19 years?" | Questions like "18th birthay" = "18 years old" or "17 years old"?)

Regards!

**Comment by DerBiasto** [comment]
Use the links on the "Statistics page".
