### ISSUE TITLE
Feature suggestion: Allow datafields to be made "public" along registered participants.

### ISSUE THREAD

**Issue by dreirund** [cde-ev/cdedb2#2]
I have a feature suggestion:

Allow for organisers of an event to specify datafields whose contents is made "public" to all registered participants who have consented to appear on the list of participants.

Rationale: Ease co-organisation of specific stuff by the whole group. For example, joint travel/ luggage transport on small events, ...

If fields that the organisers want to make public among the participants anyway are live-updated in the database, the need to manually mail around some information is not needed anymore.

And to see what others have entered fosters more inspiration than to wait until the event has started.

**Comment by DerBiasto** [comment]
Issues and feature requests are not tracked here, but in a private CdE-git.

I will migrate this and deactivate issues here entirely.

For future requests please contact cdedb@lists.cde-ev.de
